// gameConstants.js

export const GAME_CREATE_REQUEST = 'GAME_CREATE_REQUEST';
export const GAME_CREATE_SUCCESS = 'GAME_CREATE_SUCCESS';
export const GAME_CREATE_FAIL = 'GAME_CREATE_FAIL';

export const GAME_GET_ALL_REQUEST = 'GAME_GET_ALL_REQUEST';
export const GAME_GET_ALL_SUCCESS = 'GAME_GET_ALL_SUCCESS';
export const GAME_GET_ALL_FAIL = 'GAME_GET_ALL_FAIL';

export const GAME_GET_BY_ID_REQUEST = 'GAME_GET_BY_ID_REQUEST';
export const GAME_GET_BY_ID_SUCCESS = 'GAME_GET_BY_ID_SUCCESS';
export const GAME_GET_BY_ID_FAIL = 'GAME_GET_BY_ID_FAIL';

export const GAME_GET_BY_USER_REQUEST = 'GAME_GET_BY_USER_REQUEST';
export const GAME_GET_BY_USER_SUCCESS = 'GAME_GET_BY_USER_SUCCESS';
export const GAME_GET_BY_USER_FAIL = 'GAME_GET_BY_USER_FAIL';
export const GAME_LIST_MY_RESET = 'GAME_LIST_MY_RESET'